import { useRouter } from 'next/router';
import Head from 'next/head';

const Dynamic = () => {
  const router = useRouter();
  const query = router.query.dynamic;

  return (
    <div>
      <Head>
        <title>{query}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Dynamic route: {query}</h1>
    </div>
  );
};

export default Dynamic;
