import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner.js';
import Card from '../components/card.js';
import styles from '../styles/Home.module.css';
import coffeeStoresData from '../data/coffee-stores.json';

export async function getStaticProps() {
  return {
    props: { coffeeStores: coffeeStoresData },
  };
}

const options = {
  method: 'GET',
  headers: {
    Accept: 'application/json',
    Authorization: 'fsq3L0NQixGnJgQnmdYrIASfNBkYSCB5yWtH5ElKDqbDl/k=',
  },
};

fetch(
  'https://api.foursquare.com/v3/places/search?query=coffee%20shop&ll=29.739113862858495%2C-95.36883114047225',
  options
)
  .then((response) => response.json())
  .then((response) => console.log(response))
  .catch((err) => console.error(err));

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log('hi banner button');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Finder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nerby'
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.svg' width={700} height={400} />
        </div>
        {props.coffeeStores && props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl}
                    href={`/coffee-store/${coffeeStore.id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
