import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner.js';
import Card from '../components/card.js';
import styles from '../styles/Home.module.css';
// import coffeeStoresData from '../data/coffee-stores.json';

export async function getStaticProps() {
  const options = {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: 'fsq3L0NQixGnJgQnmdYrIASfNBkYSCB5yWtH5ElKDqbDl/k=',
    },
  };

  const response = await fetch(
    'https://api.foursquare.com/v3/places/search?ll=29.739113862858495%2C-95.36883114047225',
    options
  );
  const data = await response.json();
  console.log(data);

  return {
    props: { coffeeStores: data.results },
  };
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log('hi banner button');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Finder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nerby'
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.svg' width={700} height={400} />
        </div>
        {props.coffeeStores && props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Houston stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={
                      coffeeStore.imgUrl ||
                      'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80&limit=15'
                    }
                    href={`/coffee-store/${coffeeStore.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
